version: "3.9"

services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    expose:
      - "6379"
    command: redis-server --appendonly yes
    restart: always


  django:
    container_name: django
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
